FROM golang:latest AS builder
ENV GO111MODULE=on
ADD . /app
WORKDIR /app/server
COPY ./server/go.mod .
COPY ./server/go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w" -v -a -o /main ./cmd/apiserver
