export const AUTH_FETCH = 'AUTH_FETCH';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FEEDBACKS_FETCH = 'FEEDBACKS_FETCH';
export const FEEDBACKS_LOADING = 'FEEDBACKS_LOADING';
export const FEEDBACKS_ERROR = 'FEEDBACKS_ERROR';

export const CHANGE_LANG = 'CHANGE_LANG';

export const ACCOUNT_RECOVERY_FETCH = 'ACCOUNT_RECOVERY_FETCH';
export const ACCOUNT_RECOVERY_LOADING = 'ACCOUNT_RECOVERY_LOADING';
export const ACCOUNT_RECOVERY_ERROR = 'ACCOUNT_RECOVERY_ERROR';

export const GENDERS_FETCH = 'GENDERS_FETCH';
export const GENDERS_LOADING = 'GENDERS_LOADING';
export const GENDERS_ERROR = 'GENDERS_ERROR';

export const INTERESTS_FETCH = 'INTERESTS_FETCH';
export const INTERESTS_LOADING = 'INTERESTS_LOADING';
export const INTERESTS_ERROR = 'INTERESTS_ERROR';

export const ORIENTATIONS_FETCH = 'ORIENTATIONS_FETCH';
export const ORIENTATIONS_LOADING = 'ORIENTATIONS_LOADING';
export const ORIENTATIONS_ERROR = 'ORIENTATIONS_ERROR';

export const GET_LOCATION_LEGAL = 'GET_LOCATION_LEGAL';
export const GET_LOCATION_ILLEGAL = 'GET_LOCATION_ILLEGAL';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';
