export const AUTH_FETCH = 'AUTH_FETCH';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FEEDBACKS_FETCH = 'AUTH_FETCH';
export const FEEDBACKS_LOADING = 'AUTH_LOADING';
export const FEEDBACKS_ERROR = 'AUTH_ERROR';

export const CHANGE_LANG = 'CHANGE_LANG';

export const ACCOUNT_RECOVERY_FETCH = 'ACCOUNT_RECOVERY_FETCH';
export const ACCOUNT_RECOVERY_LOADING = 'ACCOUNT_RECOVERY_LOADING';
export const ACCOUNT_RECOVERY_ERROR = 'ACCOUNT_RECOVERY_ERROR';
