module.exports = {
    rules: {
        'accessor-pairs': 'warn',
        'array-callback-return': 'error',
        'block-scoped-var': 'warn',
        'class-methods-use-this': 'error',
        complexity: ['warn', 11],
        'consistent-return': 'error',
        curly: ['warn', 'all'],
        'default-case': ['error', { commentPattern: '^no default$' }],
        'dot-location': ['warn', 'property'],
        'dot-notation': ['warn', { allowKeywords: true }],
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        'guard-for-in': 'error',
        'no-alert': 'warn',
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-div-regex': 'error',
        'no-else-return': 'error',
        'no-empty-function': ['error', {
            allow: [
                'arrowFunctions',
                'functions',
                'methods',
            ]
        }],
        'no-empty-pattern': 'error',
        'no-eq-null': 'off',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-extra-label': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'error',
        'no-global-assign': ['error', { exceptions: [] }],
        'no-implicit-coercion': 'off',
        'no-implicit-globals': 'off',
        'no-implied-eval': 'error',
        'no-invalid-this': 'off',
        'no-iterator': 'error',
        'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-magic-numbers': ['warn', {
            ignore: [0, 1, -1, 100],
            ignoreArrayIndexes: false,
            enforceConst: true,
            detectObjects: false,
        }],
        'no-multi-spaces': 'error',
        'no-multi-str': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-new': 'error',
        'no-octal-escape': 'error',
        'no-octal': 'error',
        'no-param-reassign': ['warn', { props: true }],
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-restricted-properties': ['error', {
            object: 'arguments',
            property: 'callee',
            message: 'arguments.callee is deprecated',
        }, {
                property: '__defineGetter__',
                message: 'Please use Object.defineProperty instead.',
            }, {
                property: '__defineSetter__',
                message: 'Please use Object.defineProperty instead.',
            }],
        'no-return-assign': 'error',
        'no-return-await': 'error',
        'no-script-url': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unmodified-loop-condition': 'warn',
        'no-unused-expressions': ['off', {
            allowShortCircuit: false,
            allowTernary: false
        }],
        'no-unused-labels': 'error',
        'no-useless-call': 'error',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-useless-return': 'error',
        'no-void': 'off',
        'no-warning-comments': ['warn', {
            terms: ['todo', 'fixme', 'xxx'],
            location: 'start'
        }],
        'no-with': 'error',
        'prefer-promise-reject-errors': ['warn', { allowEmptyReject: true }],
        radix: 'error',
        'require-await': 'off',
        'vars-on-top': 'warn',
        'wrap-iife': ['error', 'outside', { functionPrototypeMethods: false }],
        yoda: 'error'
    }
}
